# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inventory.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Inventory(object):
    def setupUi(self, Inventory):
        Inventory.setObjectName("Inventory")
        Inventory.setFixedSize(398, 219)
        self.label = QtWidgets.QLabel(Inventory)
        self.label.setGeometry(QtCore.QRect(140, 80, 47, 13))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Designer_Files/assets//inventory.png"))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Inventory)
        self.label_3.setGeometry(QtCore.QRect(-90, -60, 581, 371))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Designer_Files/assets/inventory.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_bluecrayfish = QtWidgets.QLabel(Inventory)
        self.label_bluecrayfish.setGeometry(QtCore.QRect(23, 40, 61, 61))
        self.label_bluecrayfish.setText("")
        self.label_bluecrayfish.setPixmap(QtGui.QPixmap("Designer_Files/assets/Blue_crayfish.png"))
        self.label_bluecrayfish.setScaledContents(True)
        self.label_bluecrayfish.setObjectName("Designer_Files/assets/label_bluecrayfish")
        self.label_redcrayfish = QtWidgets.QLabel(Inventory)
        self.label_redcrayfish.setGeometry(QtCore.QRect(100, 40, 61, 61))
        self.label_redcrayfish.setText("")
        self.label_redcrayfish.setPixmap(QtGui.QPixmap("Designer_Files/assets/Red_crayfish.png"))
        self.label_redcrayfish.setScaledContents(True)
        self.label_redcrayfish.setObjectName("label_redcrayfish")
        self.label_feeds = QtWidgets.QLabel(Inventory)
        self.label_feeds.setGeometry(QtCore.QRect(160, 46, 81, 51))
        self.label_feeds.setText("")
        self.label_feeds.setPixmap(QtGui.QPixmap("Designer_Files/assets/feeds.png"))
        self.label_feeds.setScaledContents(True)
        self.label_feeds.setObjectName("label_feeds")
        self.label_5 = QtWidgets.QLabel(Inventory)
        self.label_5.setGeometry(QtCore.QRect(230, 150, 47, 13))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_booster = QtWidgets.QLabel(Inventory)
        self.label_booster.setGeometry(QtCore.QRect(240, 40, 61, 61))
        self.label_booster.setText("")
        self.label_booster.setPixmap(QtGui.QPixmap("Designer_Files/assets/boosters.png"))
        self.label_booster.setScaledContents(True)
        self.label_booster.setObjectName("label_booster")
        self.lineEdit_blueCray_amount = QtWidgets.QLineEdit(Inventory)
        self.lineEdit_blueCray_amount.setGeometry(QtCore.QRect(67, 38, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_blueCray_amount.setFont(font)
        self.lineEdit_blueCray_amount.setStyleSheet("QLineEdit {\n"
"    color: white;\n"
"    background: transparent;\n"
"    border: none;\n"
"\n"
"}\n"
"")
        self.lineEdit_blueCray_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_blueCray_amount.setObjectName("lineEdit_blueCray_amount")
        self.lineEdit_redCray_amount = QtWidgets.QLineEdit(Inventory)
        self.lineEdit_redCray_amount.setGeometry(QtCore.QRect(141, 38, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_redCray_amount.setFont(font)
        self.lineEdit_redCray_amount.setStyleSheet("QLineEdit {\n"
"    color: white;\n"
"    background: transparent;\n"
"    border: none;\n"
"\n"
"}\n"
"")
        self.lineEdit_redCray_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_redCray_amount.setObjectName("lineEdit_redCray_amount")
        self.lineEdit_feed_amount = QtWidgets.QLineEdit(Inventory)
        self.lineEdit_feed_amount.setGeometry(QtCore.QRect(210, 38, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_feed_amount.setFont(font)
        self.lineEdit_feed_amount.setStyleSheet("QLineEdit {\n"
"    color: white;\n"
"    background: transparent;\n"
"    border: none;\n"
"\n"
"}\n"
"")
        self.lineEdit_feed_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_feed_amount.setObjectName("lineEdit_feed_amount")
        self.lineEdit_booster_amount = QtWidgets.QLineEdit(Inventory)
        self.lineEdit_booster_amount.setGeometry(QtCore.QRect(280, 39, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_booster_amount.setFont(font)
        self.lineEdit_booster_amount.setStyleSheet("QLineEdit {\n"
"    color: white;\n"
"    background: transparent;\n"
"    border: none;\n"
"\n"
"}\n"
"")
        self.lineEdit_booster_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_booster_amount.setObjectName("lineEdit_booster_amount")
        self.label_3.raise_()
        self.label.raise_()
        self.label_bluecrayfish.raise_()
        self.label_redcrayfish.raise_()
        self.label_feeds.raise_()
        self.label_5.raise_()
        self.label_booster.raise_()
        self.lineEdit_blueCray_amount.raise_()
        self.lineEdit_redCray_amount.raise_()
        self.lineEdit_feed_amount.raise_()
        self.lineEdit_booster_amount.raise_()

        self.retranslateUi(Inventory)
        QtCore.QMetaObject.connectSlotsByName(Inventory)

    def retranslateUi(self, Inventory):
        _translate = QtCore.QCoreApplication.translate
        Inventory.setWindowTitle(_translate("Inventory", "Inventory"))
        self.lineEdit_blueCray_amount.setText(_translate("Inventory", "0"))
        self.lineEdit_redCray_amount.setText(_translate("Inventory", "0"))
        self.lineEdit_feed_amount.setText(_translate("Inventory", "0"))
        self.lineEdit_booster_amount.setText(_translate("Inventory", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Inventory = QtWidgets.QWidget()
    ui = Ui_Inventory()
    ui.setupUi(Inventory)
    Inventory.show()
    sys.exit(app.exec_())
