# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'market.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(531, 321)
        self.tableWidget_market = QtWidgets.QTableWidget(Form)
        self.tableWidget_market.setGeometry(QtCore.QRect(60, 40, 411, 271))
        self.tableWidget_market.setObjectName("tableWidget_market")
        self.tableWidget_market.setColumnCount(4)
        self.tableWidget_market.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_market.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_market.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_market.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_market.setHorizontalHeaderItem(3, item)
        self.label_market = QtWidgets.QLabel(Form)
        self.label_market.setGeometry(QtCore.QRect(210, 10, 90, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_market.setFont(font)
        self.label_market.setObjectName("label_market")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "market"))
        item = self.tableWidget_market.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Item"))
        item = self.tableWidget_market.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Price"))
        item = self.tableWidget_market.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Buy"))
        item = self.tableWidget_market.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Sell"))
        self.label_market.setText(_translate("Form", "MARKET"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
