# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'phone.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Phone(object):
    def setupUi(self, Phone):
        Phone.setObjectName("Phone")
        Phone.setFixedSize(331, 355)
        self.tableWidget_phone = QtWidgets.QTableWidget(Phone)
        self.tableWidget_phone.setGeometry(QtCore.QRect(10, 40, 311, 271))
        self.tableWidget_phone.setObjectName("tableWidget_phone")
        self.tableWidget_phone.setColumnCount(3)
        self.tableWidget_phone.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_phone.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_phone.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_phone.setHorizontalHeaderItem(2, item)

        self.retranslateUi(Phone)
        QtCore.QMetaObject.connectSlotsByName(Phone)

    def retranslateUi(self, Phone):
        _translate = QtCore.QCoreApplication.translate
        Phone.setWindowTitle(_translate("Phone", "Phone"))
        item = self.tableWidget_phone.horizontalHeaderItem(0)
        item.setText(_translate("Phone", "Time"))
        item = self.tableWidget_phone.horizontalHeaderItem(1)
        item.setText(_translate("Phone", "Message"))
        item = self.tableWidget_phone.horizontalHeaderItem(2)
        item.setText(_translate("Phone", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Phone = QtWidgets.QWidget()
    ui = Ui_Phone()
    ui.setupUi(Phone)
    Phone.show()
    sys.exit(app.exec_())
