# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tracker.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tracker(object):
    def setupUi(self, Tracker):
        Tracker.setObjectName("Tracker")
        Tracker.setFixedSize(833, 656)
        self.VideoLabel = QtWidgets.QLabel(Tracker)
        self.VideoLabel.setGeometry(QtCore.QRect(7, 4, 821, 621))
        self.VideoLabel.setMinimumSize(QtCore.QSize(800, 600))
        self.VideoLabel.setStyleSheet("QLabel {\n"
"    background-color: #000;\n"
"    border: 2px solid #0f0;\n"
"}")
        self.VideoLabel.setObjectName("VideoLabel")
        self.notifier = QtWidgets.QLabel(Tracker)
        self.notifier.setGeometry(QtCore.QRect(20, 624, 791, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.notifier.setFont(font)
        self.notifier.setAlignment(QtCore.Qt.AlignCenter)
        self.notifier.setObjectName("notifier")

        self.retranslateUi(Tracker)
        QtCore.QMetaObject.connectSlotsByName(Tracker)

    def retranslateUi(self, Tracker):
        _translate = QtCore.QCoreApplication.translate
        Tracker.setWindowTitle(_translate("Tracker", "Tracker"))
        self.VideoLabel.setText(_translate("Tracker", "TextLabel"))
        self.notifier.setText(_translate("Tracker", ""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Tracker = QtWidgets.QWidget()
    ui = Ui_Tracker()
    ui.setupUi(Tracker)
    Tracker.show()
    sys.exit(app.exec_())
